pipeline {
    agent any
    stages {        
        stage('Build Application') {
            steps {
                sh '/opt/maven/bin/mvn -f pom.xml clean install package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy Application') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            } 
            steps {
                sshPublisher(publishers: [sshPublisherDesc(configName: 'docker-host',
                                          transfers: [sshTransfer(cleanRemote: false, excludes: '', 
                                          execCommand: 'docker stop simple-devops-container;docker rm simple-devops-container;docker rmi simple-devops-image;docker build -t simple-devops-image .;docker run -d --name simple-devops-container -p 8081:8080 simple-devops-image', 
                                          execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '.', remoteDirectorySDF: false, removePrefix: 'webapp/target', sourceFiles: 'webapp/target/*.war')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])

            }            
        }       

    }
}
