pipeline {
    agent any
    stages {        
        stage('Build Application') {
            steps {
                sh '/opt/maven/bin/mvn -f pom.xml clean install package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy Application') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            } 
            steps {
                dir("devops/ansible") {
                    sh "pwd"
                    sh 'ansible-playbook -i hosts create-simple-devops-image.yml'
                }
                
            }            
        }       

    }
}
