pipeline {
    agent any
    stages {        
        stage('Build Application') {
            steps {
                sh '/opt/maven/bin/mvn -f pom.xml clean install package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts.... test3"
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy Application') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            } 
            steps {
                deploy adapters: [tomcat8(credentialsId: 'tomcat_user', path: '', url: 'http://54.196.50.97:8080')], contextPath: 'webapp', war: '**/*.war'
            }            
        }       

    }
}
